In [2]:
# urfu_ml_course_hw_1.md
# Конев Юрий Денисович, РИ-421002

import polars as pl

# Читаем CSV
df = pl.read_csv("train.csv")

# Типы данных и статистика 
print(df.schema) # Типы данных
print(df.describe()) # Средние, мин/макс, std и т.п.

# Пропуски
print(df.null_count())

Schema({'PassengerId': Int64, 'Survived': Int64, 'Pclass': Int64, 'Name': String, 'Sex': String, 'Age': Float64, 'SibSp': Int64, 'Parch': Int64, 'Ticket': String, 'Fare': Float64, 'Cabin': String, 'Embarked': String})
shape: (9, 13)
┌────────────┬─────────────┬──────────┬──────────┬───┬───────────┬───────────┬───────┬──────────┐
│ statistic  ┆ PassengerId ┆ Survived ┆ Pclass   ┆ … ┆ Ticket    ┆ Fare      ┆ Cabin ┆ Embarked │
│ ---        ┆ ---         ┆ ---      ┆ ---      ┆   ┆ ---       ┆ ---       ┆ ---   ┆ ---      │
│ str        ┆ f64         ┆ f64      ┆ f64      ┆   ┆ str       ┆ f64       ┆ str   ┆ str      │
╞════════════╪═════════════╪══════════╪══════════╪═══╪═══════════╪═══════════╪═══════╪══════════╡
│ count      ┆ 891.0       ┆ 891.0    ┆ 891.0    ┆ … ┆ 891       ┆ 891.0     ┆ 204   ┆ 889      │
│ null_count ┆ 0.0         ┆ 0.0      ┆ 0.0      ┆ … ┆ 0         ┆ 0.0       ┆ 687   ┆ 2        │
│ mean       ┆ 446.0       ┆ 0.383838 ┆ 2.308642 ┆ … ┆ null      ┆ 32.204208 ┆ null  ┆ null     │
│ std        ┆ 257.353842  ┆ 0.486592 ┆ 0.836071 ┆ … ┆ null      ┆ 49.693429 ┆ null  ┆ null     │
│ min        ┆ 1.0         ┆ 0.0      ┆ 1.0      ┆ … ┆ 110152    ┆ 0.0       ┆ A10   ┆ C        │
│ 25%        ┆ 224.0       ┆ 0.0      ┆ 2.0      ┆ … ┆ null      ┆ 7.925     ┆ null  ┆ null     │
│ 50%        ┆ 446.0       ┆ 0.0      ┆ 3.0      ┆ … ┆ null      ┆ 14.4542   ┆ null  ┆ null     │
│ 75%        ┆ 669.0       ┆ 1.0      ┆ 3.0      ┆ … ┆ null      ┆ 31.0      ┆ null  ┆ null     │
│ max        ┆ 891.0       ┆ 1.0      ┆ 3.0      ┆ … ┆ WE/P 5735 ┆ 512.3292  ┆ T     ┆ S        │
└────────────┴─────────────┴──────────┴──────────┴───┴───────────┴───────────┴───────┴──────────┘
shape: (1, 12)
┌─────────────┬──────────┬────────┬──────┬───┬────────┬──────┬───────┬──────────┐
│ PassengerId ┆ Survived ┆ Pclass ┆ Name ┆ … ┆ Ticket ┆ Fare ┆ Cabin ┆ Embarked │
│ ---         ┆ ---      ┆ ---    ┆ ---  ┆   ┆ ---    ┆ ---  ┆ ---   ┆ ---      │
│ u32         ┆ u32      ┆ u32    ┆ u32  ┆   ┆ u32    ┆ u32  ┆ u32   ┆ u32      │
╞═════════════╪══════════╪════════╪══════╪═══╪════════╪══════╪═══════╪══════════╡
│ 0           ┆ 0        ┆ 0      ┆ 0    ┆ … ┆ 0      ┆ 0    ┆ 687   ┆ 2        │
└─────────────┴──────────┴────────┴──────┴───┴────────┴──────┴───────┴──────────┘

In [7]:
# Кол-во пассажиров каждого класса
df.group_by("Pclass").count()

C:\Users\sl1ober\AppData\Local\Temp\ipykernel_12436\3277941218.py:2: DeprecationWarning: `GroupBy.count` was renamed; use `GroupBy.len` instead
  df.group_by("Pclass").count()

shape: (3, 2)
┌────────┬───────┐
│ Pclass ┆ count │
│ ---    ┆ ---   │
│ i64    ┆ u32   │
╞════════╪═══════╡
│ 2      ┆ 184   │
│ 3      ┆ 491   │
│ 1      ┆ 216   │
└────────┴───────┘

In [8]:
# Кол-во выживших мужчин и женщин
df.group_by(["Sex", "Survived"]).count()

C:\Users\sl1ober\AppData\Local\Temp\ipykernel_12436\934884394.py:2: DeprecationWarning: `GroupBy.count` was renamed; use `GroupBy.len` instead
  df.group_by(["Sex", "Survived"]).count()

shape: (4, 3)
┌────────┬──────────┬───────┐
│ Sex    ┆ Survived ┆ count │
│ ---    ┆ ---      ┆ ---   │
│ str    ┆ i64      ┆ u32   │
╞════════╪══════════╪═══════╡
│ male   ┆ 0        ┆ 468   │
│ female ┆ 1        ┆ 233   │
│ male   ┆ 1        ┆ 109   │
│ female ┆ 0        ┆ 81    │
└────────┴──────────┴───────┘

In [9]:
# Пассажиры старше 44 лет
print(df.filter(pl.col("Age") > 44))

shape: (115, 12)
┌─────────────┬──────────┬────────┬─────────────────────────────────┬───┬────────────┬─────────┬───────┬──────────┐
│ PassengerId ┆ Survived ┆ Pclass ┆ Name                            ┆ … ┆ Ticket     ┆ Fare    ┆ Cabin ┆ Embarked │
│ ---         ┆ ---      ┆ ---    ┆ ---                             ┆   ┆ ---        ┆ ---     ┆ ---   ┆ ---      │
│ i64         ┆ i64      ┆ i64    ┆ str                             ┆   ┆ str        ┆ f64     ┆ str   ┆ str      │
╞═════════════╪══════════╪════════╪═════════════════════════════════╪═══╪════════════╪═════════╪═══════╪══════════╡
│ 7           ┆ 0        ┆ 1      ┆ McCarthy, Mr. Timothy J         ┆ … ┆ 17463      ┆ 51.8625 ┆ E46   ┆ S        │
│ 12          ┆ 1        ┆ 1      ┆ Bonnell, Miss. Elizabeth        ┆ … ┆ 113783     ┆ 26.55   ┆ C103  ┆ S        │
│ 16          ┆ 1        ┆ 2      ┆ Hewlett, Mrs. (Mary D Kingcome… ┆ … ┆ 248706     ┆ 16.0    ┆ null  ┆ S        │
│ 34          ┆ 0        ┆ 2      ┆ Wheadon, Mr. Edward H           ┆ … ┆ C.A. 24579 ┆ 10.5    ┆ null  ┆ S        │
│ 53          ┆ 1        ┆ 1      ┆ Harper, Mrs. Henry Sleeper (My… ┆ … ┆ PC 17572   ┆ 76.7292 ┆ D33   ┆ C        │
│ …           ┆ …        ┆ …      ┆ …                               ┆ … ┆ …          ┆ …       ┆ …     ┆ …        │
│ 858         ┆ 1        ┆ 1      ┆ Daly, Mr. Peter Denis           ┆ … ┆ 113055     ┆ 26.55   ┆ E17   ┆ S        │
│ 863         ┆ 1        ┆ 1      ┆ Swift, Mrs. Frederick Joel (Ma… ┆ … ┆ 17466      ┆ 25.9292 ┆ D17   ┆ S        │
│ 872         ┆ 1        ┆ 1      ┆ Beckwith, Mrs. Richard Leonard… ┆ … ┆ 11751      ┆ 52.5542 ┆ D35   ┆ S        │
│ 874         ┆ 0        ┆ 3      ┆ Vander Cruyssen, Mr. Victor     ┆ … ┆ 345765     ┆ 9.0     ┆ null  ┆ S        │
│ 880         ┆ 1        ┆ 1      ┆ Potter, Mrs. Thomas Jr (Lily A… ┆ … ┆ 11767      ┆ 83.1583 ┆ C50   ┆ C        │
└─────────────┴──────────┴────────┴─────────────────────────────────┴───┴────────────┴─────────┴───────┴──────────┘

In [2]:
# Чтение датасета
import pandas as pd
import bottleneck as bn

df = pd.read_csv("train.csv")

# Средний возраст и стандартное отклонение (через bottleneck)
mean_age = bn.nanmean(df["Age"])
std_age = bn.nanstd(df["Age"])
print(f"Средний возраст: {mean_age:.2f}, std: {std_age:.2f}")

Средний возраст: 29.70, std: 14.52

In [4]:
# Новый столбец Fare_new (без iterrows)
df["Fare_new"] = df["Fare"] * df["Pclass"].map({1: 1.3, 2: 1.3, 3: 1.1})

In [6]:
# Оптимизация типов данных (Housing.csv)
df = pd.read_csv("Housing.csv")
# Смотрим текущие типы и использование памяти
print(df.info(memory_usage="deep"))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 221.9 KB
None

In [11]:
import pandas as pd

# Загружаем датасет
df = pd.read_csv("Housing.csv")

# Память до оптимизации
print("=== ДО оптимизации ===")
df.info(memory_usage="deep")
mem_before = df.memory_usage(deep=True).sum() / 1024**2
print(f"Память до оптимизации: {mem_before:.2f} MB")

# Копия для оптимизации
df_optimized = df.copy()

# Оптимизация типов
for col in df_optimized.columns:
    col_type = df_optimized[col].dtype
    
    if col_type == 'int64':
        df_optimized[col] = df_optimized[col].astype('int32')
    elif col_type == 'float64':
        df_optimized[col] = df_optimized[col].astype('float32')
    elif col_type == 'object':
        num_unique = df_optimized[col].nunique()
        num_total = len(df_optimized[col])
        if num_unique / num_total < 0.5:
            df_optimized[col] = df_optimized[col].astype('category')

# Проверяем память после
print("\n=== ПОСЛЕ оптимизации ===")
df_optimized.info(memory_usage="deep")
mem_after = df_optimized.memory_usage(deep=True).sum() / 1024**2
print(f"Память после оптимизации: {mem_after:.2f} MB")

# Сравнение
print(f"\nЭкономия памяти: {mem_before - mem_after:.2f} MB ({(1 - mem_after/mem_before)*100:.1f}%)")

=== ДО оптимизации ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 221.9 KB
Память до оптимизации: 0.22 MB

=== ПОСЛЕ оптимизации ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int32
 1   area              545 non-null    int32
 2   bedrooms          545 non-null    int32
 3   bathrooms         545 non-null    int32
 4   stories           545 non-null    int32
 5   mainroad          545 non-null    category
 6   guestroom         545 non-null    category
 7   basement          545 non-null    category
 8   hotwaterheating   545 non-null    category
 9   airconditioning   545 non-null    category
 10  parking           545 non-null    int32
 11  prefarea          545 non-null    category
 12  furnishingstatus  545 non-null    category
dtypes: category(7), int32(6)
memory usage: 18.1 KB
Память после оптимизации: 0.02 MB

💾 Экономия памяти: 0.20 MB (91.8%)

In [ ]:
# Выводы:
# Замена int64 → int32 и float64 → float32 уменьшила потребление памяти почти в 2 раза.
# Перевод строковых признаков (object) в категориальные (category) дал наибольший эффект.
# бщая экономия памяти составила ~45%.